### PR TITLE
Fix angular 5 error

### PR DESCRIPTION
**Pull request by dominiquemiller**
Using the Angular Quickstart Lib https://github.com/filipesilva/angular-quickstart-lib to properly publish the library.

### CODE REVIEW

**Comment by silentFred** [comment]
Awesome! Will try this out today :D

**Comment by silentFred** [comment]
@dominiquemiller i'm happy to contribute to the component if you need help

**Comment by dominiquemiller** [comment]
@silentFred Any additional features you would like to contribute to, please feel free. Open an issue / PR  and we will review! I should have this pull request merged in later today.

**Comment by dominiquemiller** [comment]
@silentFred PR has been merged, package has been released and updated to 0.5.3.  Tested with Angular 5

**Pull request merged**
